export enum MarkersIcons {
  movie = 'movie',
  cinema = 'movie',
  restaurant = 'restaurant',
  cafe = 'restaurant',
  hotel = 'hotel',
  motel = 'hotel',
  store = 'store',
  market = 'store',
  art = 'palette',
  anticafe = 'palette',
  gym = 'fitness_center',
  sport = 'fitness_center',
  pool = 'pool',
  transport = 'commute',
  taxi = 'commute',
  music = 'piano',
  nightlife = 'nightlife',
  technology = 'phonelink',
  default = 'help',
}
